### PR TITLE
Moved companies from moderators to sponsors

### PR DESCRIPTION
**Pull request by toubou91**
Details:

- didn’t find enough info for @twista 
- communities such as software craftsmanships, agilists, are still considered as moderators. only companies are listed as sponsors
- moderators who are employees of the respective sponsor companies are still considered as moderators

### CODE REVIEW

**Comment by toubou91** [comment]
#159

**Comment by rradczewski** [comment]
Thanks for the PR, sadly it breaks mobile view completely 😥

screenshot_2017-10-15-13-11-32

**Comment by rradczewski** [comment]
Furthermore, as Travis reports, we'd need to extend the schema first in order to allow a `sponsors` array in the data structure.

**Comment by toubou91** [comment]
My bad for Travis' failure, I didn't run the tests. Will fix it.

**Comment by toubou91** [comment]
@rradczewski In addition, I see that the mobile view was already broken 

comparison

**Comment by toubou91** [comment]
@rradczewski any update regarding my last comment?

**Comment by rradczewski** [comment]
Hi @toubou91, we'll be discussing this as soon as possible (we're meeting every second Monday, next week will be another meeting). If I find time until then, I will fix the mobile view in your branch so we will not hide more information than we currently do 😓 

Thanks for your contribution!

**Comment by Twista** [comment]
was mentioned here, whats going here guys ? :) cc @toubou91

**Comment by toubou91** [comment]
Nothing to worry about @Twista , sorry for this :-)

**Comment by toubou91** [comment]
@rradczewski any updates? This PR is also helpful for Utrecht right now, since we have a sponsor and we would like it to be displayed indeed as sponsor.

**Comment by rradczewski** [comment]
Rebased to latest master, added the latest events and a responsive card layout 
image

**Comment by rradczewski** [comment]
Thanks for your contribution @toubou91 👍 🎉

**Comment by toubou91** [comment]
Thanks @rradczewski , nice solution for making it responsive, btw!

**Pull request merged**
