### PR TITLE
add Toulouse 2018 event

### PR DESCRIPTION
**Pull request by GaspardPO**

### CODE REVIEW

**Comment by jdvr** [comment]
Hello @GaspardPO, thanks for submitting an event. I notice that the moderator list is empty. Who is facilitating this coderetreat?

**Comment by GaspardPO** [comment]
> Hello @GaspardPO, thanks for submitting an event. I notice that the moderator list is empty. Who is facilitating this coderetreat?

We are not sure yet.
We have 4 or 5 potential facilitators, but we will keep only 2 and the others will code.

**Comment by GaspardPO** [comment]
@jdvr I added the moderators. Could you merge it ?

**Comment by thodorisbais** [comment]
Welcome @GaspardPO , have a good one! 🎉

**Pull request merged**
