### PR TITLE
Adding the Budapest event

### PR DESCRIPTION
**Pull request by devill**
"This year, registering your event at coderetreat.org is easier than it has ever been!" >> In what universe is this process easy? It couldn't be more complicated... The UX guy in me just died of a heart attack...

### CODE REVIEW

**Comment by rradczewski** [comment]
Hi @devill, happy to hear your suggestions on how we can make it easier next year ☺️👌. So far, the transparency and semi-automation with github and Travis proved themselves to be a sustainable way of processing the over hundred events we registered this year.

In any case,  Your pr looks good, welcome to #gdcr17!

**Comment by devill** [comment]
I'm happy to give advice :D I would create a simple HTML form that sends a POST request to a server, validates it, and saves the data into a database :) To make editing existing events easy, let's use GitHub as a login provider. Google maps can be integrated with the form so that when the user types the address lat/long is automatically suggested. 

I'm happy to write that code for next years event. In fact, I just have to extract it from the Lean Poker app, since I already wrote that code :)

**Comment by devill** [comment]
Actually here is the event registration for Lean Poker: http://live.leanpoker.org/events/create

**Comment by devill** [comment]
By the way, sorry if I came off as a bit arrogant. I very rarely do that, and usually realize just a few minutes later that I did it again. It's just that I was a bit surprised by this approach. 

The HR person organizing the event had no clue how to do this, and she had to ask me. (I will be facilitating, but the organization is done by the HR person at the sponsor's end.) It might look like a funny solution to use GitHub for this process, but you have to keep in mind that many events are not organized by the developer facilitating the event. Registering the event should be accessible for non-technical people, and pull requests are not common knowledge outside our bubble.

**Pull request merged**
