### PR TITLE
Add Munich Holidu for 18

### PR DESCRIPTION
**Pull request by andreibechet**

### CODE REVIEW

**Comment by rradczewski** [comment]
Hi Andrei, welcome to GDCR18!

I assume we have the documentation wrong somewhere, as you (as well as a few others before) added an event in `_data/events/`, which isn't used this year.

Could you point me to where you found that information? (And maybe remove the file from the pull request :sweat_smile: )

**Comment by thodorisbais** [comment]
Our documentation is up-to-date:

image

But, yes, @andreibechet if you indeed saw it wrong somewhere else, please bring it up so we can cirrect it.

**Comment by andreibechet** [comment]
Oh shit ... somehow that's the old file from last year. There should also be the new file.

**Comment by andreibechet** [comment]
done, removed (sorry about that)

**Comment by rradczewski** [comment]
If any that's valuable feedback @andreibechet :) thanks a lot and welcome to #gdcr18 :)

**Pull request merged**
