### PR TITLE
Initial version of articles

### PR DESCRIPTION
**Pull request by rachelcarmena**
* Initial page to show gathered articles.
* Instructions to collaboration
* Tests to validate the format

### CODE REVIEW

**Comment by Erdbeervogel** [comment]
Hey @rachelcarmena - I've had a look and it looks great, amazing work!

I've made a couple of tweaks: 
- Made little tweaks to the table layout, as it didn't align well with table headers
- One table had city & country the wrong way
- Also would suggest to change the order of the attendees vs facilitators - under the assumption if people want to know whether it's useful attending, they'll be served first. I assume facilitators already have a motivation to host/facilitate, so they can scroll a bit more ;) 
- Added Ren & Grzegorz's twitter handles (I've pinged the latter to see if he can give his GDCR's location)

**Comment by rachelcarmena** [comment]
Awesome @Erdbeervogel , I love all of your tweaks! Thank you! You rock!! :clap:

**Comment by Erdbeervogel** [comment]
Updates: 

- Added Philip Borlin's Remote GDCR blog post. 

- Updated Navigation to link to Articles Section. I've changed it to articles/blog and added a link to the old blog post section at the end of the page, until we migrate the relevant blog post over. Given the last blog post was from July 2017 I realised having a more up to date articles page would be beneficial in the top navigation.

**Comment by rradczewski** [comment]
👍 On merging it! 😍🎉

Couple of small things, but no blockers:

- the cards layout on mobile looks a bit empty if fields are left empty
- city & country could be joined, there's no benefit in separating them here in contrast to the list of events
- "blog/article"  has been there before so it didn't feel appropriately exciting to see it, given how much more valuable the content now is. Maybe "Voices" or "Testimonials" would resonate more with me, but not a biggie 🤷‍♀️

**Comment by rachelcarmena** [comment]
Thanks again @Erdbeervogel !! :clap: 

Thanks @rradczewski! Done:

* Fixed the layout on mobile (separation from events list)
* I've joined city and country in only one column
* From `Blog to `Blog/Articles`. From `Blog/Articles` to `Articles` :wink:

Please, let me know if you agree in order to squash all the little commits into a single commit to merge in the master branch. 

Thanks again!!

**Pull request merged**
