### PR TITLE
added gdcr17 event at University of Applied Science at Fulda

### PR DESCRIPTION
**Pull request by tpd-opitz**

### CODE REVIEW

**Comment by rradczewski** [comment]
Hi @tpd-opitz,
thanks for creating your event in Fulda! 
It looks like the extra fields (`details` and `description`) are causing some problems with escaping. We're not using them anyway, so you could just go ahead and remove them completely :)

Furthermore, I'm curious about why you chose Doodle as your RSVP platform. Most events are using ti.to, eventbrite or meetup.com so they can charge a deposit, which helps with no-shows.

Cheers,
Raimo

**Comment by tpd-opitz** [comment]
Hello Raimo,
> It looks like the extra fields (details and description) are causing some problems with escaping.  

The problems came from improper character encoding when transferring the file from windows to linux for the npm test. 

> We're not using them anyway, so you could just go ahead and remove them completely :)  

So how do I add details as show for the currently 2 events here: http://coderetreat.org/events ?

>  I'm curious about why you chose Doodle as your RSVP platform. Most events are using ti.to, eventbrite or meetup.com so they can charge a deposit...  

I don't want to charge a deposit since my events in 2015 and 2016 hat 0 and 6 attendees so that "no-shows" did not affect registrations. I'd like the barrier being low for this year...

BTW:
at he the event page there are only 2 of the  4 events (before mine) visible. How is that?


bye
Thomas

**Comment by rradczewski** [comment]
Hi Thomas,

we're in the process of shutting down the social network at **coderetreat.org**, which is why there is no way to create a new event there.

**gdcr.coderetreat.org** will soon become **coderetreat.org** and replace the existing network. You can see all events on [this preliminary page](http://gdcr.coderetreat.org/events/) as we continue working on the page.

**Comment by tpd-opitz** [comment]
> we're in the process of shutting down the social network at coderetreat.org, which is why there is no way to create a new event there.

I know ;o)

> You can see all events on this preliminary page as we continue working on the page.

My understanding was that the new "github" process fills the schedule at the old location.

Its a bit confusing to see this years events at the old location while it is meant to die entirely...

bye  
Thomas

**Pull request merged**
