### PR TITLE
Create Beijing.json

### PR DESCRIPTION
**Pull request by yugangbai**
Global Day of Code Retreat 2018 Beijing

### CODE REVIEW

**Comment by rradczewski** [comment]
Looks good, welcome to GDCR18!

**Comment by rradczewski** [comment]
Looks good, welcome!

**Comment by yugangbai** [comment]
Thanks a lot

**Comment by yugangbai** [comment]
I’m very sorry. Nokia Beijing Technical Center can’t host GDCR2018 in Beijing because of some reason. Could you please help remove Beijing.json.

Thanks a lot

From: Bai, Yugang (NSB - CN/Beijing)
Sent: Tuesday, October 23, 2018 5:07 PM
To: coderetreat/coderetreat.github.io <reply@reply.github.com>; coderetreat/coderetreat.github.io <coderetreat.github.io@noreply.github.com>
Cc: Author <author@noreply.github.com>; Qu, Steven (NSB - CN/Beijing) <steven.qu@nokia-sbell.com>; Zhao, Hongli (NSB - CN/Beijing) <hongli.zhao@nokia-sbell.com>; Chen, Samuel Y. (NSB - CN/Beijing) <samuel.y.chen@nokia-sbell.com>; Wang, Demi (NSB - CN/Beijing) <demi.wang@nokia-sbell.com>
Subject: RE: [coderetreat/coderetreat.github.io] Create Beijing.json (#401)

Thanks a lot

**Pull request merged**
