### PR TITLE
Added Zielona Gora, Poland

### PR DESCRIPTION
**Pull request by p-zalejko**

### CODE REVIEW

**Comment by rradczewski** [comment]
Hi, thanks for submitting the Pull Request! I'm not sure about updating the package-lock right in the same PR, would you please remove the changes to that file?

**Comment by rradczewski** [comment]
Woops, the file shouldn't be completely removed from the repo. I'm not on a computer right now, but I'll happily manually merge your PR tomorrow.

**Comment by p-zalejko** [comment]
sorry, my mistake, I did not want to remove it (wrong button ;) ) I will fix it soon

**Comment by rradczewski** [comment]
Perfect, thanks!

**Pull request merged**
