### PR TITLE
Adding Codurance as facilitator

### PR DESCRIPTION
**Pull request by rachelcarmena**

### CODE REVIEW

**Comment by rradczewski** [comment]
Hi @rachelcarmena, who from codurance will be facilitating? We'd like to have people get to know the moderators, not the hosting companies ☺️

**Comment by rachelcarmena** [comment]
Hi @rradczewski, nice to meet you (or better said, nice to answer you :smile: ) I will facilitate it (@bberrycarmen), but I have and I'll have the help of other colleagues from Codurance, and I've seen that others have put the hosting company and... I wouldn't want to have the limelight :sweat_smile: But I understand you and I'll accept your decision with this PR. Absolutely. Thanks for keeping this event year after year!!

**Comment by rradczewski** [comment]
Hey 😄,
thanks for the heads-up, you're totally right in that there are other events with companies in the `moderators` field. Your event just happened to be the first where I noticed it 😅 

I'll of course merge your Pull Request, but we might decide to remove the companies from all events in the future.

Hope you'll have a great time at your event! If you need anything or want to exchange thoughts with other organizers around the world, there's #coderetreat on the Software Crafters Slack 👍

**Comment by rachelcarmena** [comment]
Thank you @rradczewski !! Dancing for joy, right now :dancer: 

But I understand your decision in the future (if nobody mentions hosting company, I won't feel this feeling to make this PR :sweat_smile:) 

I'll check #coderetreat on the Software Crafters Slack. Thanks for your advice!! It's a pleasure to share this motivation for GDCR :wink:

**Pull request merged**
