### PR TITLE
 update Bucharest craftsmanship - align title with other Romanian events.

### PR DESCRIPTION
**Pull request by victorrentea**
update Bucharest craftsmanship - align title with other Romanian events.

### CODE REVIEW

**Comment by victorrentea** [comment]
It's just a rename of my event.

I will re-fork and update and do another PR on monday.

Thank you!

Victor Rentea
Independent Technical Trainer, Lead Architect at IBM
www.victorrentea.ro
(+4) 0720019564

PS: Written on a tiny device. Please excuse any tpyos and abbrev

**Comment by thodorisbais** [comment]
Then there is no need to re-fork. You can just rename the file and commit that change. 😃

**Comment by thodorisbais** [comment]
@victorrentea I know you've been busy with Devoxx, hence, congrats for the winning best talk award!
Looks like I was in such a rush that I misunderstood the entire concept. In any case, we can have it like that.

**Comment by victorrentea** [comment]
Thanks. No worries. It was just a detail. Naming :)
You know that quote... :P

Thanks !

*Victor Rentea*
Independent Trainer, Lead Architect at IBM
(+4) 0720 019 564
www.victorrentea.ro
Follow me <https://twitter.com/victorrentea> to grow!
<https://ro.linkedin.com/in/victor-rentea-9339364a>

**Comment by victorrentea** [comment]
Honestly I'm rehearsing just now some GOL constraints for tomorrow :)
You caught me !

Good luck to everyone tomorrow!

*Victor Rentea*
Independent Trainer, Lead Architect at IBM
(+4) 0720 019 564
www.victorrentea.ro
Follow me <https://twitter.com/victorrentea> to grow!
<https://ro.linkedin.com/in/victor-rentea-9339364a>

**Comment by thodorisbais** [comment]
Heheh, you see?! The clock started ticking already! Counting doooown! 🕙 
Enjoy tomorrow and hope to get a connection with Bucharest via the video booths!

**Pull request merged**
